services:

  app:
    image: ghcr.io/radu-c-martin/maybe:latest
    ports:
      - 3000:3000
    restart: unless-stopped
    env_file:
      - .env
    environment:
      RUN_DB_MIGRATIONS_IN_BUILD_STEP: "false"
      DB_HOST: "postgres"
      HOSTING_PLATFORM: "localhost"
      DISABLE_SSL: "true"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER:?}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
